services:
  courier:
    image: registry.cn-hangzhou.aliyuncs.com/top-herio/herio:latest
    container_name: courier
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - courier_data:/app/data
    environment:
      - TZ=Asia/Shanghai

volumes:
  courier_data:
